[package]
name = "octree-file"
version = "0.1.0"
authors = ["Philipp Mildenberger <philipp.mildenberger@student.uibk.ac.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
